import Image1 from "../src/assets/productBimgthree.png"
import Image2 from "../src/assets/productSimgthree.png"
import Image3 from "../src/assets/productSimgtwo.png"
import Image4 from "../src/assets/productSimgone.png"
import Image5 from "../src/assets/productimg5.png"
import Image6 from "../src/assets/productBimgfour.png"
import Image7 from "../src/assets/productSimgfour.png"
import Image8 from "../src/assets/productimg6.png"
import Image9 from "../src/assets/productimg1.jpg"

let data = [
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 9,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 10,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image8,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 11,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image9,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 12,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 1,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image1,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 2,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image2,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 3,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 4,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image4,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 5,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image5,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 7,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image7,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 8,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image3,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
  {
  id: 6,
  title: "Basic Crew Neck Tee",
  price: '$44.00',
  colorType: 'Black',
  image: Image6,
  addWishList: 'Add to Wish List',
  compare: 'Compare',
  addCart: 'Add to Cart',
  badge: 'New'
  },
]

export default data